In a new file (test_sagittal_brain.py) define an input and expected numpy arrays to test Charlene's code.

Take a look to the diagram on the previous issue (#24) to understand what Charlene is trying to do.

Think why the current input (brain_sample.csv) and output (brain_average.csv) files that Charlene's been using to test her code are not very useful, and create new ones that could highlight any common error in this type of data manipulation.

Hint
Which array can you define that will produce different average values for each different row?

In [22]:
%%writefile test_sagittal_brain.py

import numpy as np
import sagittal_brain as sb

 

def test_run_averages():
    sample_data = np.array([[0., 0., 0], [4., 5., 6.], [7., 8., 9.]]) 
    np.savetxt("brain_sample.csv", sample_data, fmt='%.1f', delimiter=',')
    sb.run_averages("brain_sample.csv", "brain_average.csv" )
    result=np.loadtxt("brain_average.csv", delimiter=',')
    
    expected = np.array([3.66666667, 4.33333333, 5.0])
    assert np.testing.assert_array_equal(result, expected)
    
    
    
    


Overwriting test_sagittal_brain.py


In [20]:
sample_data = np.array([[0., 0., 0], [4, 5, 6], [7, 8, 9]]) 
np.savetxt("brain_sample.csv", sample_data, fmt='%d', delimiter=',')
np.loadtxt("brain_average.csv", delimiter=',')


array([3.7, 4.3, 5. ])

In [24]:




import subprocess
subprocess.run(["pytest", "test_sagittal_brain.py"])    



python(26197) MallocStackLogging: can't turn off malloc stack logging because it was not enabled.


============================= test session starts ==============================
platform darwin -- Python 3.13.5, pytest-8.3.4, pluggy-1.5.0
rootdir: /Users/idilgozel/sagittal_average
plugins: anyio-4.7.0, cov-7.0.0
collected 1 item

test_sagittal_brain.py F                                                 [100%]

=================================== FAILURES ===================================
______________________________ test_run_averages _______________________________

    def test_run_averages():
        sample_data = np.array([[0., 0., 0], [4., 5., 6.], [7., 8., 9.]])
        np.savetxt("brain_sample.csv", sample_data, fmt='%.1f', delimiter=',')
        sb.run_averages("brain_sample.csv", "brain_average.csv" )
        result=np.loadtxt("brain_average.csv", delimiter=',')
    
        expected = np.array([3.66666667, 4.33333333, 5.0])
>       assert np.testing.assert_array_equal(result, expected)

test_sagittal_brain.py:14: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

CompletedProcess(args=['pytest', 'test_sagittal_brain.py'], returncode=1)

In [27]:
%%writefile -a test_sagittal_brain.py




import subprocess
subprocess.run(["pytest", "test_sagittal_brain.py"])    

result = subprocess.run(
    ["python", "-m", "sagittal_brain", "brain_sample.csv", "-o", "brain_average.csv"],
    capture_output=True,
    text=True,
)
print(result.stdout)
print(result.stderr)
print(result.returncode) 


Appending to test_sagittal_brain.py


In [ ]:
print(result.stdout)
print(result.stderr)
print(result.returncode)    




0


Bring what's needed from test_call_command.py to test_sagittal_brain.py so that when calling this script the following happens:

a good input 20x20 array is created (input);
an expected array with 20 elements is created (expected);
the input array is saved as a csv file (brain_sample.csv);
Charlene's code is executed from within this script (using subprocess);
the output produced by Charlene's code (brain_average.csv) is read into output; and
test that output and expected are equal.
run that script from the bash terminal.

In [4]:
%%writefile test_call_command.py

import subprocess

import numpy as np 
import sagittal_brain as sb

def test_call_command():
    
    
    
input= np.zeros((20,20))
expected = np.array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
np.savetxt("brain_sample.csv", input, fmt='%.1f', delimiter=',')    
    result = subprocess.run(["python", "sagittal_brain.py", "brain_sample.csv", "-o", "brain_average.csv"]
)
    print(result.stdout)
    print(result.stderr)
    print(result.returncode)
    assert result.returncode == 0
    output = np.loadtxt("brain_average.csv", delimiter=',')
    np.testing.assert_array_equal(output, expected)
    
    
    




Overwriting test_call_command.py


In [2]:
import numpy as np

data_input = np.zeros((20, 20))
data_input[-1, :] = 1
np.savetxt("brain_sample.csv", data_input, fmt='%d', delimiter=',')

In [3]:
import sagittal_brain as sb
sb.run_averages("brain_sample.csv", "brain_average.csv" )   

In [1]:
%%writefile pyproject.toml

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Sagittal Brain"
version = "0.1.0"

[tool.hatch.build.targets.wheel]
packages = [
  "src/sagittal_brain",
]

Writing pyproject.toml


In [2]:
%%writefile __init__.py
from .sagittal_brain import run_averages
__all__ = ["run_averages"]



Writing __init__.py


In [10]:
import numpy as np
m= np.random.randint(0,5, (5,5))
m

array([[2, 1, 1, 3, 1],
       [2, 0, 3, 3, 3],
       [1, 2, 1, 4, 2],
       [4, 0, 1, 4, 0],
       [0, 1, 0, 0, 3]])

In [11]:
m[0]

array([2, 1, 1, 3, 1])